// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ExpenseTracker.Domain.Entities;

public partial class Category
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string? Name { get; set; }

    public string? Icon { get; set; }

    public string? Color { get; set; }

    public bool? IsSystem { get; set; }

    public DateTime? CreatedDate { get; set; }
}