// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ExpenseTracker.Domain.Entities;

public partial class Expense
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int CategoryId { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; } = null!;

    public DateTime ExpenseDate { get; set; }

    public string? Description { get; set; }

    public bool? IsRecurring { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? Timestamp { get; set; }
}